services:
  postgres:
    image: postgres:17
    container_name: local-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d app"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
        - war

  gateway:
    build:
      dockerfile: Dockerfile
      args:
        CMD: gateway
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://app:app@postgres:5432/app?sslmode=disable
    networks:
      - war
      - web

  scraper:
    build:
      dockerfile: Dockerfile
      args:
        CMD: scraper
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      gateway:
        condition: service_started
    environment:
      DATABASE_URL: postgres://app:app@postgres:5432/app?sslmode=disable
      WARERA_API_KEY: ${WARERA_API_KEY}
    networks:
      - war

  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - gateway
    networks:
      - web

volumes:
  postgres_data:
  caddy_data:
  caddy_config:

networks:
  war:
  web:
